# Generated by Django 5.0.6 on 2024-09-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('platinum', 'Platinum')], max_length=10)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.event')),
            ],
        ),
    ]
