# Generated by Django 5.0.6 on 2024-09-02 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_tickettype_booknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.events'),
        ),
    ]
