# Generated by Django 5.0.6 on 2024-09-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_dummybanks'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummybanks',
            name='cvv_number',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
