# Generated by Django 5.0.6 on 2024-09-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_dummybanks_cvv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummybanks',
            name='atm_card_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
