# Generated by Django 5.0.6 on 2024-09-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_alter_dummybanks_atm_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummybanks',
            name='account_status',
        ),
        migrations.RemoveField(
            model_name='dummybanks',
            name='user',
        ),
    ]
