# Generated by Django 5.0.6 on 2024-09-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_events_ticket_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
