# Generated by Django 5.0.6 on 2024-09-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummybank',
            name='event',
        ),
        migrations.RemoveField(
            model_name='dummybank',
            name='user',
        ),
        migrations.DeleteModel(
            name='DummyBanks',
        ),
        migrations.DeleteModel(
            name='DummyBank',
        ),
    ]
