# Generated by Django 5.0.6 on 2024-09-16 04:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booknow',
            name='booking_serial',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
