# Generated by Django 5.0.6 on 2024-09-16 12:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_rename_canceled_booknow_is_cancelled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNoww',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('starter', 'Starter'), ('standard', 'Standard'), ('platinum', 'Platinum')], max_length=10)),
                ('number_of_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('ticket_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('booking_serial', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
