# Generated by Django 5.0.6 on 2024-09-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_booknoww'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookNow',
        ),
    ]
