# Generated by Django 5.0.6 on 2024-09-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0017_delete_booknow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknoww',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpanel.events'),
        ),
    ]
