# Generated by Django 5.1.1 on 2024-10-29 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_alter_booknoww_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='completion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
