# Generated by Django 5.1.1 on 2024-10-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_events_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
